### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by finid** [plexydesk/plexydesk#17]
I  don't see any instruction on how to compile Plexydesk.

Thanks,

**Comment by siraj** [comment]
https://github.com/plexydesk/plexydesk/wiki/PlexyDesk-Build-Guide :). let me know if you run into any issues.

**Comment by siraj** [comment]
btw, if you need flicker image search to work, get a free developer key from Flickr and pass it to cmake as -DSOCIAL_KIT_FLICKR_API_KEY="xxxxx". This will let you search Flickr feeds.

**Comment by finid** [comment]
Thanks,  but even for an experienced Linux user, a command like the one given for building it is a head-spinner. What is a new Liunx user supposed to make of this:

```
mkdir build cd build cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release make sudo make install
```

That's at least 5 commands, right?

Please edit it so that it makes sense.
- mkdir build
- cd build
- cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
- make
- sudo make install (or `su` to root, then `make install`)

**Comment by siraj** [comment]
Since we are at the very start of the project, we don't have many user documentation so the the link i sent is mostly for developer who are familiar with cmake and Qt. But I agree that the documentation is too vague. Also the current wikipages on github is edible by every one, if you like you can help by improving it :) which would be awesome. 

Thank you very much :)

**Comment by finid** [comment]
Ok, once I succeed in installing it, I'll update the doc and write a blog post about it.

**Comment by siraj** [comment]
Thank you very munch :)

**Comment by finid** [comment]
Ok, so I got past that error, but encountered another one after running `make`.

```
In file included from /home/kamit/Downloads/plexydesk-master/base/uikit/core/desktopactivity.h:7:0,
                 from /home/kamit/Downloads/plexydesk-master/base/uikit/core/view_controller.h:9,
                 from /home/kamit/Downloads/plexydesk-master/base/uikit/core/extensionmanager.h:28,
                 from /home/kamit/Downloads/plexydesk-master/base/uikit/themepackloader.cpp:29:
/home/kamit/Downloads/plexydesk-master/base/uikit/core/widget.h:84:10: error: ‘std::function’ has not been declared
     std::function<void (InputEvent a_type,
          ^
/home/kamit/Downloads/plexydesk-master/base/uikit/core/widget.h:84:18: error: expected ‘,’ or ‘...’ before ‘<’ token
     std::function<void (InputEvent a_type,
                  ^
base/uikit/CMakeFiles/PlexyDeskUICore.dir/build.make:77: recipe for target 'base/uikit/CMakeFiles/PlexyDeskUICore.dir/themepackloader.cpp.o' failed
make[2]: *** [base/uikit/CMakeFiles/PlexyDeskUICore.dir/themepackloader.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'base/uikit/CMakeFiles/PlexyDeskUICore.dir/all' failed
make[1]: *** [base/uikit/CMakeFiles/PlexyDeskUICore.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

Looks like minor coding stuff. Please fix and push.

**Comment by siraj** [comment]
The fix is in progress we merged a large patch. if you stay on #plexydesk on freenode you will get the notification when it's fixed :).

**Comment by finid** [comment]
Thanks, I'll hang out here and download the latest zip file when it's released.

**Comment by siraj** [comment]
@finid  I'm moving the error to #27 since it'a a new issue

**Comment by finid** [comment]
cool!

**Comment by siraj** [comment]
@finid fixed

**Comment by finid** [comment]
Nice! I'll give it another shot.
