### ISSUE TITLE
Error compiling on Fedora 

### ISSUE THREAD

**Issue by finid** [plexydesk/plexydesk#18]
Ran into some issues compiling the master on Fedora (KDE), after installing all the dependencies, which was a lot.

First it spewed this error:

```
CMake Error at CMakeLists.txt:278 (ADD_SUBDIRECTORY):
  add_subdirectory given source "activity-runner" which is not an existing
  directory
```

After some head-scratching, I renamed the `runner` directory to `activity-runner` and tried again. Then it gave this error:

```
CMake Error: File /home/kamit/Downloads/plexydesk-master/runner/plexydesk.cmake.desktop does not exist.
CMake Error at CMakeLists.txt:198 (CONFIGURE_FILE):
  configure_file Problem configuring file


CMake Error: File /home/kamit/Downloads/plexydesk-master/activity-runner/activity-runner.cmake.desktop does not exist.
CMake Error at CMakeLists.txt:204 (CONFIGURE_FILE):
  configure_file Problem configuring file


-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Failed
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Failed
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Failed
CMake Error at CMakeLists.txt:270 (ADD_SUBDIRECTORY):
  add_subdirectory given source "runner" which is not an existing directory.
```

So it appears that  it's expecting both a  `runner`and an `activity-runner`  directory, but if I make a copy of `runner` and name that `activity-runner`, it rightly complains about duplicate targets.

How do I proceed with this? 

TIA

**Comment by siraj** [comment]
The compilation should work with Qt 5.3 or 5.4 SDK's. If you run into problems with Fedora let me know the version of fedora and the Qt version you installed so I can give it a try.

Thank you :+1:
